swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /nmap/:
    get:
      tags:
      - nmap
      description: create object
      operationId: NmapController.Create
      responses:
        "200":
          description: '{string} success'
        "403":
          description: body is empty
    post:
      tags:
      - nmap
      description: create object
      operationId: NmapController.Create
      parameters:
      - in: body
        name: body
        description: The object content
        required: true
        schema:
          $ref: '#/definitions/models.Scanner'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Scanner'
        "403":
          description: body is empty
definitions:
  models.Object:
    title: Object
    type: object
    properties:
      ObjectId:
        type: string
      PlayerName:
        type: string
      Score:
        type: integer
        format: int64
  models.Profile:
    title: Profile
    type: object
    properties:
      Address:
        type: string
      Age:
        type: integer
        format: int64
      Email:
        type: string
      Gender:
        type: string
  models.Scanner:
    title: Scanner
    type: object
    properties:
      args:
        type: array
        items:
          type: string
      cmd:
        type: string
      command:
        type: string
      result:
        type: string
  models.User:
    title: User
    type: object
    properties:
      Id:
        type: string
      Password:
        type: string
      Profile:
        $ref: '#/definitions/models.Profile'
      Username:
        type: string
